version: "3"

services:
  discord-bot:
    image: lolog.azurecr.io/lolog-discord:0.2.0
    environment:
      - MONGO_URL=db:27017
      - LOL_CLIENT_VERSION=10.2.1
    links:
      - backend:lolog-backend
      - db
  db:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data-volume:/data/db"
  backend:
    image: lolog.azurecr.io/lolog-back:0.1.0
    environment:
      - API_KEY
    ports:
      - "4000:4000"
volumes:
  mongo-data-volume:
